all:	
	pdflatex dokumentace.tex
	pdflatex dokumentace.tex
	
	rm -r dokumentace.aux dokumentace.log dokumentace.toc dokumentace.synctex.gz
	chmod +x remove_excess.sh

clean:
	rm -r dokumentace.aux dokumentace.log dokumentace.toc dokumentace.synctex.gz
